### ISSUE TITLE
Adding a title name in a plot is not working

### ISSUE THREAD

**Issue by yujung-c** [jmw86069/venndir#10]
Hi, recently I have updated this package. 
Everything works fine. But, title() doesn't work in plotting process.
I had used title() for adding a title in a Venn diagram in the previous version of venndir(). But, now doesn't work.
How can I add title in the Venn diagram based on the Jamba tool?

```
library(venndir)
main='title'
venndir(make_venn_test(100, 2, do_signed=TRUE),
              proportional=TRUE, do_plot = T,
              overlap_type="each", font_cex=1.2)
title(main)
```

It shows this error message.
`Error in title(main = main) : plot.new has not been called yet`

I appreciate for your helps and thank for your recent update :) .

**Comment by jmw86069** [comment]
Thank you for posting, this is a great point. I need to add the option for a title to `venndir()` and `render_venndir()`.

Currently the best way to add a title is with `grid` functions like this:
```R
library(venndir)
main = "Venn Title"
venndir(make_venn_test(50, 3))
grid::grid.text(x=0.5, y=0.9,
   label=main,
   gp=grid::gpar(fontsize=18, fontface="bold"))
```

I added the fontsize and fontface to show how to customize these values.

One reason to add the title to `venndir()` is so the title will be drawn for each plot, if the plot is used in a multi-panel figure. I will add it to my short list. For now, hopefully `grid::grid.text()` will suit your needs.

**Comment by jmw86069** [comment]
Just to close this out, there is now a `main` argument in `venndir()` used to set the plot title.
To use a custom title, use the steps above to add `grid::grid.text()` to the plot device afterwards.
