### ISSUE TITLE
Encounter with error message 

### ISSUE THREAD

**Issue by yujung-c** [jmw86069/venndir#7]
Hi, recently I use your packages and encounter with this error message:

` vo <- venndir(yy, proportional=TRUE, do_plot=FALSE);
 render_venndir(vo)`
Error in render_venndir(vo) : 
  Element 'venn_jp' must inherit from 'JamPolygon'.

But, it works fine when i run this code.
` vo <- venndir(yy, proportional=TRUE, do_plot=T);`

Also, I try the test. Still has error message.
`library(venndir)`
`setlist<- make_venn_test(100, 3)`
`vo <- venndir(setlist)`
`render_venndir(vo)`
Error in render_venndir(vo) : 
  Element 'venn_jp' must inherit from 'JamPolygon'.

I appreciate for your helps and thank for your great work :) .

**Comment by jmw86069** [comment]
Ah thank you for reporting. I have been updating the code to remove `sp` and `rgeos`, this introduced a regression.
I'll report back when fixed.

**Comment by jmw86069** [comment]
The bug is fixed, but let me know if you encounter errors or have questions about how to do something.
And thank you for reporting the error!
